### ISSUE TITLE
Add srun task (in adition to sbatch)

### ISSUE THREAD

**Issue by jmrgonza** [uwefladrich/scriptengine-tasks-hpc#16]
I believe that it would be helpful to provide an script-engine `srun` task, in adition to the available `sbatch`.

The purpose of that task would be to execute certain operations in parallel, with script-engine waiting until completion for the execution of the next task. I think that some operations that are done in the ecearth pipeline would benefit from this option. For example, it would be possible (with some changes) to build the runtime directory with script-engine running on the login node (no sbatch yet), then build the oasis weights with a call to a `srun` task, wait for the weight files to be ready, and then initiate the model in a batch job initiated with `sbatch`.

I do not know how this could be implemented, but the idea would be to have some construct that could be invoked like this (for execution of a list of commands in the fractional queue in hpc-2020):

```yaml
- hpc.slurm.srun:
    opts:
        ntasks: 4
        qos: nf
    do:
       - base.echo:
            msg: "This is running in parallel!"
       - base.command:
            name: "hostname"
```
