### ISSUE TITLE
Add support for PBS batch system

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine-tasks-hpc#2]
The title says it. A new SE task is needed to submit jobs for the Portable Batch System (PBS).

**Comment by uwefladrich** [comment]
The SLURM/sbatch task is quite flexible by passing the task arguments to the `sbatch` command (other than `scripts` and `submit_from_batch_job`). PBS/qsub supports unfortunately only one-letter arguments but in order to keep the same flexibility, it should do the same. It just looks ab bit more strange, e.g.
```yaml
hpc.pbs.qsub:
    A: <account_name>
    o: <stdout_path>
    e: <stderr_path>
    l: walltime=10:30,mem=320kb
```
