### ISSUE TITLE
Add support for SLURM hetereogeneous jobs

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine-tasks-hpc#5]
`hpc.slurm.sbatch` should support [SLURM hetereogeneous jobs](https://slurm.schedmd.com/heterogeneous_jobs.html). This means that colon-separated options and arguments need to be handled by the task.

**Comment by uwefladrich** [comment]
The suggested syntax would be:
```yaml
hpc.slurm.sbatch:
    <general options>
    hetjob_spec:
        <list of hetjob opts+args>
```

for example:
```yaml
hpc.slurm.sbatch:
    account: foo
    time: 100
    output: foo.out
    hetjob_spec:
        - nodes: 1
        - nodes: 2
        - nodes: 1
```
which would translate to
```
sbatch \
  --account foo --time 100 --output foo.out \
  --nodes 1 : --nodes 2 : --nodes 1
```
and queue a heterogeneous job with three hetjob components on one, two, and one nodes, respectively.
