### ISSUE TITLE
hpc.slurm.sbatch fails with complex hetjob specs

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine-tasks-hpc#6]
The following `hetjob_spec` example doesn't work:
```yaml
hpc.slurm.sbatch:
    # [...]
    hetjob_spec:
        - {
            nodes: 1,
            ntasks-per-node: 16,
        }
        - nodes: 1
```
because the command line for the `sbatch` is build incorrectly. In particular, a ':' is added between the `--nodes 1` and `--ntasks-per-node 16` argument in the first hetjob group.
